services:
  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: {$POSTGRES_USER}
      POSTGRES_PASSWORD: {$POSTGRES_PASSWORD}
      POSTGRES_DB: {$POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./app
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
